# Generated by Django 5.2.11 on 2026-02-06 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("assets", "0005_add_ai_category_is_new"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_approve_users", "Can approve user registrations")
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account was approved or rejected",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved or rejected this account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set to True when user clicks email verification link",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for rejection, if applicable",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="requested_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department selected during registration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_by_users",
                to="assets.department",
            ),
        ),
    ]
