# Generated by Django 5.2.11 on 2026-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_set_existing_users_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="organisation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External organisation (e.g., 'NUCMS')",
                max_length=200,
            ),
        ),
    ]
