# Generated by Django 5.2.11 on 2026-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakesession",
            name="confirmed_assets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Assets confirmed present during this stocktake",
                related_name="stocktake_confirmations",
                to="assets.asset",
            ),
        ),
    ]
