# Generated by Django 5.2.11 on 2026-02-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_add_stocktake_confirmed_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="home_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this asset lives when not checked out",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_assets",
                to="assets.location",
            ),
        ),
        migrations.AddField(
            model_name="assetimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="thumbnails/"
            ),
        ),
    ]
