# Generated by Django 5.2.11 on 2026-02-06 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_asset_home_location_assetimage_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="idx_asset_status"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["created_at"], name="idx_asset_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["condition"], name="idx_asset_condition"
            ),
        ),
        migrations.AddIndex(
            model_name="assetimage",
            index=models.Index(
                fields=["asset", "is_primary"],
                name="idx_assetimage_asset_primary",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["timestamp"], name="idx_transaction_timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["action"], name="idx_transaction_action"
            ),
        ),
    ]
