# Generated by Django 5.2.11 on 2026-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assets",
            "0004_asset_idx_asset_status_asset_idx_asset_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetimage",
            name="ai_category_is_new",
            field=models.BooleanField(
                default=False,
                help_text="True when AI suggests a category not found in the database",
            ),
        ),
    ]
