# Generated by Django 5.2.11 on 2026-02-06 21:26

from django.db import migrations, models

import assets.models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_add_ai_category_is_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True,
                        help_text="Logo for light backgrounds (SVG or PNG, max 500 KB)",
                        null=True,
                        upload_to="branding/",
                        validators=[assets.models.validate_logo_file_size],
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Logo for dark backgrounds (SVG or PNG, max 500 KB)",
                        null=True,
                        upload_to="branding/",
                        validators=[assets.models.validate_logo_file_size],
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (PNG or ICO, max 100 KB)",
                        null=True,
                        upload_to="branding/",
                        validators=[assets.models.validate_favicon_file_size],
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Branding",
            },
        ),
    ]
