# Generated by Django 5.2.11 on 2026-02-06 22:46

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_add_sitebranding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_checkout_asset", "Can check out assets"),
                    ("can_checkin_asset", "Can check in assets"),
                    ("can_print_labels", "Can print asset labels"),
                    ("can_merge_assets", "Can merge duplicate assets"),
                    ("can_export_assets", "Can export asset data"),
                    (
                        "can_handover_asset",
                        "Can hand over assets between borrowers",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="assetimage",
            name="ai_name_suggestion",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_backdated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("checkout", "Check Out"),
                    ("checkin", "Check In"),
                    ("transfer", "Transfer"),
                    ("audit", "Audit"),
                    ("handover", "Handover"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_backdated"], name="idx_transaction_is_backdated"
            ),
        ),
    ]
