# Generated by Django 5.2.11 on 2026-02-06 22:48

from django.db import migrations


def backfill_created_at(apps, schema_editor):
    """Set created_at = timestamp for all existing transactions."""
    from django.db.models import F

    Transaction = apps.get_model("assets", "Transaction")
    Transaction.objects.filter(created_at__isnull=True).update(
        created_at=F("timestamp")
    )


def create_borrower_group(apps, schema_editor):
    """Create the Borrower group if it doesn't exist."""
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Borrower")


class Migration(migrations.Migration):

    dependencies = [
        (
            "assets",
            "0007_alter_asset_options_assetimage_ai_name_suggestion_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            backfill_created_at,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_borrower_group,
            migrations.RunPython.noop,
        ),
    ]
