# Generated by Django 5.2.11 on 2026-02-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_backfill_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
