# Generated by Django 5.2.11 on 2026-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_alter_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetimage",
            name="ai_department_is_new",
            field=models.BooleanField(
                default=False,
                help_text="True when AI suggests a department not in the provided list",
            ),
        ),
        migrations.AddField(
            model_name="assetimage",
            name="ai_department_suggestion",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
