# Generated by Django 5.2.11 on 2026-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_assetimage_ai_department_is_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="lost_stolen_notes",
            field=models.TextField(
                blank=True,
                help_text="Details about loss or theft circumstances",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Expected return date for checkouts",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("disposed", "Disposed"),
                    ("missing", "Missing"),
                    ("lost", "Lost"),
                    ("stolen", "Stolen"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("checkout", "Check Out"),
                    ("checkin", "Check In"),
                    ("transfer", "Transfer"),
                    ("relocate", "Relocate"),
                    ("audit", "Audit"),
                    ("handover", "Handover"),
                ],
                max_length=20,
            ),
        ),
    ]
