# Generated by Django 5.2.11 on 2026-02-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_add_lost_stolen_statuses_due_date_relocate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_kit",
            field=models.BooleanField(
                default=False,
                help_text="This asset is a kit containing other assets",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_serialised",
            field=models.BooleanField(
                default=False,
                help_text="Track individual serial units for this asset",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of units in this transaction"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="serial_barcode",
            field=models.CharField(
                blank=True,
                help_text="Denormalised barcode snapshot of the serial",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("checkout", "Check Out"),
                    ("checkin", "Check In"),
                    ("transfer", "Transfer"),
                    ("relocate", "Relocate"),
                    ("audit", "Audit"),
                    ("handover", "Handover"),
                    ("kit_return", "Kit Return"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AssetSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "barcode_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="barcodes/serial/"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("missing", "Missing"),
                            ("lost", "Lost"),
                            ("stolen", "Stolen"),
                            ("disposed", "Disposed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "lost_stolen_notes",
                    models.TextField(
                        blank=True,
                        help_text="Details about loss or theft circumstances",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serials",
                        to="assets.asset",
                    ),
                ),
                (
                    "checked_out_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrowed_serials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serials",
                        to="assets.location",
                    ),
                ),
            ],
            options={
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="AssetKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "is_kit_only",
                    models.BooleanField(
                        default=False,
                        help_text="Component can only be checked out as part of this kit",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_of_kits",
                        to="assets.asset",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_components",
                        to="assets.asset",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific serial unit if component is serialised",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kit_memberships",
                        to="assets.assetserial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="serial",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific serial unit for serialised assets",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="assets.assetserial",
            ),
        ),
        migrations.AddIndex(
            model_name="assetserial",
            index=models.Index(
                fields=["asset", "status"], name="idx_serial_asset_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetserial",
            constraint=models.UniqueConstraint(
                fields=("asset", "serial_number"),
                name="unique_serial_per_asset",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetkit",
            constraint=models.UniqueConstraint(
                fields=("kit", "component"), name="unique_kit_component"
            ),
        ),
    ]
