# Generated by Django 5.2.11 on 2026-02-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_asset_is_kit_asset_is_serialised_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="is_serialised",
            field=models.BooleanField(
                default=True,
                help_text="Track individual serial units for this asset",
            ),
        ),
    ]
