# Generated by Django 5.2.11 on 2026-02-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_is_serialised_default_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="barcode_prefix",
            field=models.CharField(
                blank=True,
                help_text="Barcode prefix for assets in this department",
                max_length=10,
            ),
        ),
    ]
