# Generated by Django 5.2.11 on 2026-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_department_barcode_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetimage",
            name="detail_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="detail_thumbnails/"
            ),
        ),
    ]
