# Generated by Django 5.2.11 on 2026-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0015_add_detail_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="accent_color",
            field=models.CharField(
                blank=True, help_text="Accent brand colour (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="color_mode",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("auto", "Auto"),
                ],
                default="auto",
                help_text="Default colour mode for the site",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="Primary brand colour (hex, e.g. #4F46E5)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                help_text="Secondary brand colour (hex)",
                max_length=7,
            ),
        ),
    ]
