# Generated by Django 5.2.11 on 2026-02-16 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0017_add_holdlist_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="holdlistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial__isnull", True)),
                fields=("hold_list", "asset"),
                name="unique_holdlist_asset_no_serial",
            ),
        ),
    ]
