# Generated by Django 5.2.11 on 2026-02-16 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0019_holdlist_fk_fixes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether this asset is visible in public listings",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="public_description",
            field=models.TextField(
                blank=True,
                help_text="Description shown in public listings",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="barcode_prefix",
            field=models.CharField(
                blank=True,
                help_text="Barcode prefix for assets in this department",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitebranding",
            name="color_mode",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("system", "System"),
                ],
                default="system",
                help_text="Default colour mode for the site",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Expected return date for checkouts",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                condition=models.Q(("is_public", True)),
                fields=["is_public"],
                name="idx_asset_is_public",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["is_kit"], name="idx_asset_is_kit"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["is_serialised"], name="idx_asset_is_serialised"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="unique_top_level_location_name",
            ),
        ),
    ]
