# Generated by Django 5.2.11 on 2026-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0020_asset_is_public_asset_public_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetimage",
            name="ai_suggestions_applied",
            field=models.BooleanField(
                default=False,
                help_text="True when AI suggestions have been applied to the asset",
            ),
        ),
    ]
