# Generated by Django 5.2.11 on 2026-02-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0021_ai_suggestions_applied"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("can_checkout_asset", "Can check out assets"),
                    ("can_checkin_asset", "Can check in assets"),
                    ("can_print_labels", "Can print asset labels"),
                    ("can_merge_assets", "Can merge duplicate assets"),
                    ("can_export_assets", "Can export asset data"),
                    (
                        "can_handover_asset",
                        "Can hand over assets between borrowers",
                    ),
                    (
                        "override_hold_checkout",
                        "Can override hold list checkout block",
                    ),
                ],
            },
        ),
    ]
