# Generated by Django 5.2.11 on 2026-02-16 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0023_virtualbarcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StocktakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("confirmed", "Confirmed"),
                            ("missing", "Missing"),
                            ("unexpected", "Unexpected"),
                        ],
                        default="expected",
                        max_length=20,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocktake_items",
                        to="assets.asset",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stocktake_items",
                        to="assets.assetserial",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="assets.stocktakesession",
                    ),
                ),
            ],
            options={
                "ordering": ["asset__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "asset", "serial"),
                        name="unique_stocktake_item",
                    )
                ],
            },
        ),
    ]
