# Generated by Django 5.2.11 on 2026-02-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0024_stocktakeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfctag",
            name="serial",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific serial unit (V479: COULD)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nfc_tags",
                to="assets.assetserial",
            ),
        ),
    ]
