# Generated by Django 5.2.11 on 2026-02-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0025_nfctag_serial_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktakesession",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stocktake_sessions",
                to="assets.department",
            ),
        ),
    ]
