# Generated by Django 5.2.11 on 2026-02-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0026_stocktake_department_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("checkout", "Check Out"),
                    ("checkin", "Check In"),
                    ("transfer", "Transfer"),
                    ("relocate", "Relocate"),
                    ("audit", "Audit"),
                    ("handover", "Handover"),
                    ("kit_return", "Kit Return"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
