# Generated by Django 5.2.11 on 2026-02-20 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0028_printclient_printrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printrequest",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
