# Generated by Django 5.2.11 on 2026-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0030_seed_holdlist_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="is_serialised",
            field=models.BooleanField(
                default=False,
                help_text="Track individual serial units for this asset",
            ),
        ),
    ]
