# Generated by Django 5.2.11 on 2026-02-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0031_is_serialised_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="printclient",
            name="protocol_version",
            field=models.CharField(default="1", max_length=10),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="label_type",
            field=models.CharField(
                choices=[("asset", "Asset"), ("location", "Location")],
                default="asset",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printrequest",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="print_requests",
                to="assets.location",
            ),
        ),
    ]
