# Generated by Django 5.2.11 on 2026-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0032_protocol_v2_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_checkable",
            field=models.BooleanField(
                default=False,
                help_text="If True, this location can be checked out as a unit (all assets checked out to a single borrower).",
            ),
        ),
    ]
