# Generated by Django 5.2.11 on 2026-02-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0035_backfill_can_be_borrower"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
